version: "3.7"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: starter-project
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
